# Generated by Django 2.2 on 2019-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='info',
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=5000),
        ),
    ]
