# Generated by Django 2.2 on 2019-04-20 15:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casinoapp', '0002_auto_20190420_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=django.contrib.auth.models.User, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
