# Generated by Django 2.2 on 2019-04-20 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casinoapp', '0003_auto_20190420_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
