# Generated by Django 2.2 on 2019-04-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinoapp', '0004_auto_20190420_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='points',
        ),
    ]
